pixelant/pxa_social_feed

Classes/Utility/Exeption/ServerCommunicationException.php, Classes/Utility/RequestUtility.php, Classes/Utility/Task/ImportTaskUtility.php, Resources/Private/Language/locallang.xlf
here's the functionality for getting instagram hashtag feed. It was present on branch for 6.2, but not here.
also small namespace fix for ServerCommunicationException added
=> [FEATURE] added instagram hashtag feeds functionality + namespaces fix

Classes/Utility/Task/ImportTaskUtility.php
=> [BUGFIX] set post url for twitter feed, fixes #11

Classes/ViewHelpers/ParseMessageViewHelper.php, Resources/Private/Partials/Frontend/FeedsItems.html
ViewHelper parse feed message and converts `#hashtags`, `@mentions` and `www.some.url` to anchors
=> Feed message parser view helper

Classes/Utility/Task/ImportTaskUtility.php
https://developer.twitter.com/en/docs/tweets/tweet-updates
=> Show full text for tweets over 140 char

composer.json, ext_emconf.php
=> [TASK] Set author to "Pixelant"

Resources/Private/Partials/Backend/TokenInfo/Type2.html
This corrects the permissions for fetching Instagram posts.
=> [BUGFIX] Fix permissions necessary for Instagram

Resources/Private/Partials/Backend/TokenInfo/Type1.html
This corrects the permissions for fetching Facebook posts.
Resolves: #85
=> [BUGFIX] Fix permissions necessary for Facebook

Classes/Controller/EidController.php, Classes/ViewHelpers/FacebookLoginUrlViewHelper.php
Fixes: #101
Handle http protocol properly in Facebook login
=> [BUGFIX] Handle http protocol properly in Facebook login

Classes/Domain/Model/Token.php
Fixes: #105
Add missing property ''expires'' to AccessToken.
=> [BUGFIX] Add missing property ''expires'' to AccessToken

Classes/Domain/Model/Token.php, Classes/ViewHelpers/FacebookLoginUrlViewHelper.php
Fixes: #105
Add check for if long lived Facebook token is ''expired''.
=> [BUGFIX] Add check for if long lived Facebook token is ''expired''

Classes/Domain/Model/Configuration.php, Classes/Domain/Model/Feed.php, Classes/Domain/Validation/Validator/ConfigurationValidator.php, Classes/Feed/Update/InstagramFeedUpdater.php, Configuration/TCA/tx_pxasocialfeed_domain_model_configuration.php, Configuration/TCA/tx_pxasocialfeed_domain_model_feed.php, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/Administration/EditConfiguration.html, ext_tables.sql
store Insta Images to fileadmin
after merging, you need to:
1. re-install the ext [so DB tables will get updated]
2. add fileadmin/socialmedia/instacontent/normal  and  fileadmin/socialmedia/instacontent/small folders
3. run pxa_social_feed scheduler task
TODO: i didnt know how to minify the files. tried php ('imagejpeg' fn) and imagemagick -  it didnt work
so it stores 'small' and 'normal' images but they're both the same.
you will probably need to minify them to get this task done.
the comment about it 's left in 'InstagramFeedUpdater'
=> Bls insta images

composer.json
Fixes: #117 
Lock version for league/oauth2-facebook.
=> [TASK] Lock version for league/oauth2-facebook

Classes/Feed/Source/InstagramSource.php
Fix issue with not being able to fetch Instagram business account ID.
=> [BUGFIX] Fix issue with not being able to fetch Instagram business account ID

Classes/Feed/Update/InstagramFeedUpdater.php
Fixes: #121
Make sure that Instagram images are displayed in frontend.
=> [BUGFIX] Make sure that Instagram images are displayed in frontend

.gitattributes
The `.gitattributes` file keeps development files out of packaging
(= they are not installed with composer for a stable version).
=> [TASK] Add .gitattributes file

Documentation/Settings.cfg, composer.json
Prepare for version ''3.1.4''.
=> [RELEASE] Prepare for version ''3.1.4''

.github/workflows/ter-release.yml
Add Github Action TER release.
=> [TASK] Add Github Action TER release

Classes/ViewHelpers/ParseMessageViewHelper.php, Tests/Unit/ViewHelpers/ParseMessageViewHelperTest.php
Hashtags or mention containing unicode characters are now properly detected.
Also, links are now correctly escaped and opened with `rel="noreferrer"`.
Fixes #36
=> [BUGFIX] Fix parsing of message with unicode characters

Classes/ViewHelpers/ParseMessageViewHelper.php
=> [BUGFIX] Fix PHPCGL issues

Classes/Domain/Model/Token.php
=> [TASK] variable type for facebook could be null

Configuration/TCA/tx_pxasocialfeed_domain_model_configuration.php, Configuration/TCA/tx_pxasocialfeed_domain_model_feed.php, Configuration/TCA/tx_pxasocialfeed_domain_model_token.php
=> [BUGFIX]: use core extension for label

Classes/Service/Task/ImportFeedsTaskService.php
I added a new Social Media Provider in my own extension and i want to extend the task without the boilerplate code.
=> [TASK] make it easier to extends Task Service

Classes/Feed/Source/FacebookSource.php, Classes/Feed/Update/FacebookFeedUpdater.php
It's better to get the correct link from Facebook instead of building it yourself. I had cases where the link was not correct.
=> [TASK]: Get post url direct from the facebook api

Classes/Controller/EidController.php
Add missing scope for page access for Facebook.
=> [BUGFIX] Add missing scope for page access for Facebook

Classes/Service/Notification/NotificationService.php
- Proper usage of the mailer api (fix an exception on v11)
- Using system address in from allows to pass SPF filters
=> [BUGFIX] Fix sending of the notification email

Resources/Private/Language/locallang.xlf
=> [TASK] Remove duplicated trans-unit

Classes/Controller/AdministrationController.php, Classes/Controller/EidController.php, Classes/Domain/Model/FacebookPage.php, Classes/Domain/Model/FacebookUser.php, Classes/Domain/Model/Token.php, Classes/Domain/Repository/TokenRepository.php, Classes/Feed/Source/FacebookSource.php, Classes/Provider/Facebook.php, Classes/Service/Task/ImportFeedsTaskService.php, Configuration/Services.yaml, Configuration/TCA/tx_pxasocialfeed_domain_model_token.php, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Backend/ListTokens.html, Resources/Private/Partials/Backend/TokenInfo/Type5.html, Resources/Private/Templates/Administration/EditConfiguration.html, ext_tables.sql
=> [FEATURE] Add support for facebook page token

.gitignore
No actual change to the code was made. Only the .vscode folder was added to the git ignore rules.
Fixes: #160
=> [TASK] Add VSCode folder to git ignore

Classes/ViewHelpers/ParseMessageViewHelper.php
The Hashtag Links in Facebook Page post was not correct converted
=> [BUGFIX] Handle hashtag conversion for page token correct

Resources/Public/Icons/type-5-icon.svg
The Icon for token type "Facebook Page" was missing
=> [BUGFIX] Add missing icon for facebook page type

composer.json
The scheduler module is required for the import task.
=> [TASK]: add typo3/cms-scheduler as dependency

Classes/Domain/Model/Feed.php
=> [BUGFIX] Set correct doc type

Classes/Feed/Update/InstagramFeedUpdater.php
The code has been modified to ensure that the storage folders for downloading images always exist. Previously, the code directly retrieved the folders, which could lead to errors if the folders were not available. Now, the code checks if the folders exist using their respective identifiers and creates them if they do not exist.
=> [TASK] Ensure instacontent download folders exist

Classes/Controller/EidController.php, Classes/Domain/Model/FacebookUser.php, Classes/Provider/Facebook.php
In order for the extension to continue working with TYPO3 v10, the functions need to be adjusted as TYPO3 v10 can still run on PHP 7.3.
=> [BUGFIX] Removed functions only available from PHP 7.4 onwards

Classes/Controller/AdministrationController.php, Classes/Feed/FacebookFeedFactory.php, Classes/Feed/InstagramFactory.php, Classes/Feed/TwitterFactory.php, Classes/Feed/YoutubeFactory.php, Classes/Service/Task/ImportFeedsTaskService.php, Classes/Utility/ConfigurationUtility.php, Tests/Unit/Feed/FacebookFeedFactoryTest.php, Tests/Unit/Feed/InstagramFactoryTest.php, Tests/Unit/Feed/TwitterFactoryTest.php, Tests/Unit/Feed/YoutubeFactoryTest.php
I remove all the imports thats are not needed
=> [Task] Remove unused imports

Resources/Private/Templates/Administration/Index.html, Resources/Public/JavaScript/Backend/SocialFeedModule.js
The navigation between the tabs was a little bit clunky
=> [BUGFIX] handle tab navigation in backend better

Resources/Public/JavaScript/Backend/SocialFeedModule.js
The selected page was not set correctly in the input field.
setFormValueFromBrowseWin is deprecated in 10 and will be removed later.
https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/10.2/Deprecation-89331-FormEngineLegacyFunctions.html
=> [BUGFIX] Fill selected folder or page correct

Classes/Domain/Model/Token.php
PR is pending https://github.com/thephpleague/oauth2-facebook/pull/75
https://github.com/pixelant/pxa_social_feed/issues/168
=> [BUGFIX] Exception has wrong inheritance

Resources/Private/Language/locallang_db.xlf
The labels are defined in the tca, but do not exist.
=> [BUGFIX] Add missing localization labels

Classes/Domain/Model/Configuration.php, Classes/Service/Task/ImportFeedsTaskService.php, Configuration/TCA/tx_pxasocialfeed_domain_model_configuration.php, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Templates/Administration/EditConfiguration.html, ext_tables.sql
We don't want the feeds to be deleted after importing, so I've now added a flag for this."
=> [FEAT] Allow users to enable/disable clean-up after importing feeds

Classes/Controller/AdministrationController.php, Classes/Controller/FeedsController.php, Classes/Domain/Model/Configuration.php, Classes/Domain/Repository/ConfigurationRepository.php, Classes/Domain/Repository/FeedRepository.php, Classes/Feed/Update/FacebookFeedUpdater.php, Classes/Task/AdditionalFieldProviderTrait.php, Classes/Task/ImportTask.php, Classes/Task/ImportTaskAdditionalFieldProvider.php, Classes/Utility/SchedulerUtility.php, Classes/ViewHelpers/EditorRestrictionEnabledViewHelper.php
I have started to adjust the types for php stan lvl 9
=> [TASK] Update and fix types

Classes/Domain/Model/Feed.php, Classes/Domain/Model/FileReference.php, Classes/Domain/Model/Token.php, Classes/Feed/Update/BaseUpdater.php, Classes/Feed/Update/FacebookFeedUpdater.php, Classes/Feed/Update/InstagramFeedUpdater.php, Classes/Feed/Update/TwitterFeedUpdater.php, Classes/Feed/Update/YoutubeFeedUpdater.php, Configuration/Extbase/Persistence/Classes.php, Configuration/TCA/tx_pxasocialfeed_domain_model_feed.php, Resources/Private/Language/locallang_db.xlf, Resources/Private/Partials/Frontend/FeedItemCard.html, Resources/Private/Partials/Frontend/FeedItemDynamic.html, ext_tables.sql
This function saves all images as file references so that you can crop the image and define a focus point.
=> Store images as reference

Classes/Domain/Model/Feed.php, Classes/Domain/Model/FileReference.php, Classes/Feed/Update/BaseUpdater.php, Classes/Feed/Update/FacebookFeedUpdater.php, Classes/Feed/Update/InstagramFeedUpdater.php, Classes/Feed/Update/TwitterFeedUpdater.php, Classes/Feed/Update/YoutubeFeedUpdater.php
I forgot to check if the file reference is already set.
=> [BUGFIX] Prevent duplicate references from being set

Classes/Domain/Model/Token.php, Classes/Domain/Validation/Validator/TokenValidator.php, Classes/Feed/Source/TwitterV2Source.php, Classes/Feed/TwitterV2Factory.php, Classes/Feed/Update/TwitterV2FeedUpdater.php, Classes/Service/Task/ImportFeedsTaskService.php, Classes/ViewHelpers/ParseMessageViewHelper.php, Configuration/TCA/tx_pxasocialfeed_domain_model_token.php, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Partials/Backend/TokenEdit/Type6.html, Resources/Private/Partials/Backend/TokenInfo/Type6.html, Tests/Unit/Feed/TwitterV2FactoryTest.php, ext_tables.sql
Resolves #186
This PR add support for Twitter API V2.
A valid Twitter account with at least a "Basic" tier in needed in order to use the new v2 endpoint.
=> [WIP] [FEATURE] Handling of Twitter API v2

Classes/Domain/Model/Configuration.php, Classes/Feed/Source/FacebookSource.php, Configuration/TCA/tx_pxasocialfeed_domain_model_configuration.php, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Templates/Administration/EditConfiguration.html, ext_tables.sql
https://github.com/pixelant/pxa_social_feed/issues/191
=> Added support for Facebooks posts end point

composer.json
This extensions eequired minimal php 7.4
=> [TASK] Set required minimal php version

Classes/Feed/Update/BaseUpdater.php
fixes: 
https://github.com/pixelant/pxa_social_feed/issues/197
=> use url instead of baseUrl

Classes/Domain/Repository/FeedRepository.php
=> Fix Request Variable Check order for scheduler as CLI
